=begin

we have 2 ways to print output
1.print
2.puts(adds \n at end)
  2.1 we can use also use short hand notation 'p' for puts
=end

puts "this output is generated by puts(has newline at end)"
print "this output is generated by print(no new line at end)"
